[phases.setup]
nixPkgs = ["python310", "gcc", "gfortran", "openblas", "lapack"]

[phases.install]
cmds = ["cd model && pip install -r requirements.txt"]

[start]
cmd = "cd model && python detect_server.py"